name: Build Executables

on:
  push

jobs:
  build_win:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install raylib
        run: |
          choco install raylib -y

      - name: Compile
        run: |
          g++ *.cpp -o game.exe -lraylib -lopengl32 -lgdi32 -lwinmm

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: game-windows
          path: game-win.exe
    
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install raylib
        run: |
          sudo apt-get update
          sudo apt-get install -y libraylib-dev

      - name: Compile
        run: |
          g++ *.cpp -o game -lraylib -lGL -lm -lpthread -ldl

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          path: game
          name: game-linux